#!/usr/bin/env bash

# https://github.com/flying-sheep/react-color-scheme-switch/pull/3
# https://github.com/yarnpkg/berry/issues/4045
pdir="$(realpath "$(dirname -- "$0")/..")"
export NODE_OPTIONS="--no-warnings --require=\"$pdir/.pnp.cjs\" --experimental-loader=\"$pdir/.pnp.loader.mjs\""
exec node "$@"
